"""Create Game Model

Revision ID: fa8bb8ab5ce7
Revises: b2e116f98932
Create Date: 2023-10-01 09:36:12.276456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa8bb8ab5ce7'
down_revision = 'b2e116f98932'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
